version: "3.2"
services:

  reel_game:
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${SERVER_PORT:-15500}
        target: 15500
    environment:
      - JWT_SECRET=$JWT_SECRET
      - DB_HOST=mongo_reel
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PWD=$DB_PWD
      - DOCKER_ENV=true
    depends_on:
      - mongo_reel

  mongo_reel:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PWD
    ports:
      - "28017:27017"
    volumes:
      - max_min:/data/db

volumes:
  max_min:
